run:
  skip-files:
    - "main.go"
output:
  sort-results: true
  format: checkstyle:lint-report.out
linters:
  enable-all: true
  disable:
    - maligned
    - golint
    - varcheck
    - scopelint
    - deadcode
    - structcheck
    - interfacer
    - ifshort
    - exhaustivestruct
    - nosnakecase
    - exhaustruct
    - gci
    - depguard
    - goerr113
    - tagliatelle
    - wrapcheck
    - unconvert
    - noctx
    - gochecknoglobals
    - forcetypeassert
    - paralleltest
    - wastedassign
    - gofumpt
