name: Feature Request
description: Suggest a new feature or document a project's feature card
title: "[FEATURE]: "
projects:
  - 42dx/1
labels:
  - enhancement
  - triage
body:
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: |
        **High level description stating what is to be achieved with the requested feature.**
      placeholder: |
        When I need to achieve 'this', it is a complex/demanding task due to [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        **A clear and concise description of what you want to happen. It is interesting to write this 'impersonating' the most beneficiated stakeholder's point of view.**
      placeholder: As a <developer|manager|qa|etc>, I want to be able to `<desired behavior>`, so that <final goal of the feature>.
    validations:
      required: true

  - type: textarea
    id: workarounds
    attributes:
      label: Alternatives / Workarounds
      description: |
        **A clear and concise description of any alternative solutions, features, jury-rigs or whatever else you may have considered to be able to achieve the proposed solution.**
      placeholder: I have used another package for that, but it had worse issues. also tried to implement by myself but [...]
    validations:
      required: false

  - type: textarea
    id: criteria
    attributes:
      label: Acceptance Criteria
      description: |
        **Unordered checkbox list of criteria to be checked before closing the issue as completed.**
      value: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        **Add any other context, screenshots/videos or any extra info about the feature request here.**
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        **Unordered list of reference (links) to support the implementation.**
      value: |
        -
        -
        -
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
